/* Copyright (c) 2023 Rick (rick 'at' gibbed 'dot' us)
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would
 *    be appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and must not
 *    be misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 *    distribution.
 */

using System;

namespace Gibbed.Starfield.PluginFormats
{
    public static class FormTypes
    {
        private static readonly FormType[] _FormTypes;

        static FormTypes()
        {
            _FormTypes = new[]
            {
                FormType.NONE,
                FormType.TES4,
                FormType.GRUP,
                FormType.GMST,
                FormType.KYWD,
                FormType.FFKW,
                FormType.LCRT,
                FormType.AACT,
                FormType.TRNS,
                FormType.TXST,
                FormType.GLOB,
                FormType.DMGT,
                FormType.CLAS,
                FormType.FACT,
                FormType.AFFE,
                FormType.HDPT,
                FormType.EYES,
                FormType.RACE,
                FormType.SOUN,
                FormType.SECH,
                FormType.ASPC,
                FormType.AOPF,
                FormType.SKIL,
                FormType.MGEF,
                FormType.SCPT,
                FormType.LTEX,
                FormType.PDCL,
                FormType.ENCH,
                FormType.SPEL,
                FormType.SCRL,
                FormType.ACTI,
                FormType.TACT,
                FormType.CURV,
                FormType.CUR3,
                FormType.ARMO,
                FormType.BOOK,
                FormType.CONT,
                FormType.DOOR,
                FormType.INGR,
                FormType.LIGH,
                FormType.MISC,
                FormType.STAT,
                FormType.SCOL,
                FormType.PKIN,
                FormType.MSTT,
                FormType.GRAS,
                FormType.FLOR,
                FormType.FURN,
                FormType.WEAP,
                FormType.AMMO,
                FormType.NPC_,
                FormType.LVLN,
                FormType.LVLP,
                FormType.KEYM,
                FormType.ALCH,
                FormType.IDLM,
                FormType.BMMO,
                FormType.NOTE,
                FormType.PROJ,
                FormType.HAZD,
                FormType.BNDS,
                FormType.SLGM,
                FormType.TERM,
                FormType.LVLI,
                FormType.GBFT,
                FormType.GBFM,
                FormType.LVLB,
                FormType.WTHR,
                FormType.WTHS,
                FormType.CLMT,
                FormType.SPGD,
                FormType.REGN,
                FormType.NAVI,
                FormType.CELL,
                FormType.REFR,
                FormType.ACHR,
                FormType.PMIS,
                FormType.PARW,
                FormType.PGRE,
                FormType.PBEA,
                FormType.PFLA,
                FormType.PCON,
                FormType.PPLA,
                FormType.PBAR,
                FormType.PEMI,
                FormType.PHZD,
                FormType.WRLD,
                FormType.NAVM,
                FormType.TLOD,
                FormType.DIAL,
                FormType.INFO,
                FormType.QUST,
                FormType.IDLE,
                FormType.PACK,
                FormType.CSTY,
                FormType.LSCR,
                FormType.LVSP,
                FormType.ANIO,
                FormType.WATR,
                FormType.EFSH,
                FormType.TOFT,
                FormType.EXPL,
                FormType.DEBR,
                FormType.IMGS,
                FormType.IMAD,
                FormType.FLST,
                FormType.PERK,
                FormType.BPTD,
                FormType.ADDN,
                FormType.AVIF,
                FormType.CAMS,
                FormType.CPTH,
                FormType.VTYP,
                FormType.MATT,
                FormType.IPCT,
                FormType.IPDS,
                FormType.ARMA,
                FormType.LCTN,
                FormType.MESG,
                FormType.RGDL,
                FormType.DOBJ,
                FormType.DFOB,
                FormType.LGTM,
                FormType.MUSC,
                FormType.FSTP,
                FormType.FSTS,
                FormType.SMBN,
                FormType.SMQN,
                FormType.SMEN,
                FormType.DLBR,
                FormType.MUST,
                FormType.DLVW,
                FormType.WOOP,
                FormType.SHOU,
                FormType.EQUP,
                FormType.RELA,
                FormType.SCEN,
                FormType.ASTP,
                FormType.OTFT,
                FormType.ARTO,
                FormType.MATO,
                FormType.MOVT,
                FormType.DUAL,
                FormType.COLL,
                FormType.CLFM,
                FormType.REVB,
                FormType.RFGP,
                FormType.AMDL,
                FormType.AAMD,
                FormType.MAAM,
                FormType.LAYR,
                FormType.COBJ,
                FormType.OMOD,
                FormType.ZOOM,
                FormType.INNR,
                FormType.KSSM,
                FormType.SCCO,
                FormType.AORU,
                FormType.STAG,
                FormType.IRES,
                FormType.BIOM,
                FormType.NOCM,
                FormType.LENS,
                FormType.LSPR,
                FormType.OVIS,
                FormType.DLYR,
                FormType.STND,
                FormType.STMP,
                FormType.GCVR,
                FormType.MRPH,
                FormType.TRAV,
                FormType.RSGD,
                FormType.OSWP,
                FormType.ATMO,
                FormType.LVSC,
                FormType.SPCH,
                FormType.RESO,
                FormType.AAPD,
                FormType.VOLI,
                FormType.SFBK,
                FormType.SFPC,
                FormType.SFPT,
                FormType.SFTR,
                FormType.PCMT,
                FormType.BMOD,
                FormType.STBH,
                FormType.PNDT,
                FormType.IUTF,
                FormType.CNDF,
                FormType.PCBN,
                FormType.PCCN,
                FormType.STDT,
                FormType.WWED,
                FormType.RSPJ,
                FormType.AOPS,
                FormType.AMBS,
                FormType.WBAR,
                FormType.PTST,
                FormType.LMSW,
                FormType.FORC,
                FormType.TMLM,
                FormType.EFSQ,
                FormType.SDLT,
                FormType.MTPT,
                FormType.CLDF,
                FormType.FOGV,
                FormType.WKMF,
                FormType.LGDI,
                FormType.PSDC,
                FormType.SUNP,
                FormType.PMFT,
                FormType.TODD,
                FormType.AVMD,
                FormType.PERS,
                FormType.CHAL,
            };
        }

        public static FormType GetTypeFromIndex(int index)
        {
            if (index < 0 || index >= _FormTypes.Length)
            {
                throw new ArgumentOutOfRangeException(nameof(index));
            }
            return _FormTypes[index];
        }
    }
}
